version: "3.7"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    
  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ~/database/zipper:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4584:4566-4584"
      - 8080:8080
    environment:
      - SERVICES=s3
    volumes:
      - ./.aws:/docker-entrypoint-initaws.d